baseurl = "" 
title = "EMBRAINED | Synthetic Agency"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  #logo = "fa-laptop"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/company/110520989/"

[[params.social]]
  medium = "bluesky"
  icon = "cloud" # approximation, check theme icons
  link = "https://bsky.app/profile/embrained.ai"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://x.com/embrainedai"

[languages]
[languages.en]
languageName = "English"
weight = 1


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

#[module]
#  [[module.imports]]
#    path = "hugo-module-gallery-grid"

#[module]
#  [[module.imports]]
#   path = "hugo-shortcode-gallery"

